/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapRouteImport } from './routes/map'
import { Route as LotsRouteImport } from './routes/lots'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LotsDeviceIdRouteImport } from './routes/lots.$deviceId'
import { Route as BookingNewRouteImport } from './routes/booking.new'
import { Route as BookingIdTicketRouteImport } from './routes/booking.$id.ticket'
import { Route as BookingIdPayRouteImport } from './routes/booking.$id.pay'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicVnpayReturnRouteImport } from './routes/api/public/vnpay/return'
import { Route as ApiPublicVnpayIpnRouteImport } from './routes/api/public/vnpay/ipn'

const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LotsRoute = LotsRouteImport.update({
  id: '/lots',
  path: '/lots',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LotsDeviceIdRoute = LotsDeviceIdRouteImport.update({
  id: '/$deviceId',
  path: '/$deviceId',
  getParentRoute: () => LotsRoute,
} as any)
const BookingNewRoute = BookingNewRouteImport.update({
  id: '/booking/new',
  path: '/booking/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdTicketRoute = BookingIdTicketRouteImport.update({
  id: '/booking/$id/ticket',
  path: '/booking/$id/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdPayRoute = BookingIdPayRouteImport.update({
  id: '/booking/$id/pay',
  path: '/booking/$id/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVnpayReturnRoute = ApiPublicVnpayReturnRouteImport.update({
  id: '/api/public/vnpay/return',
  path: '/api/public/vnpay/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVnpayIpnRoute = ApiPublicVnpayIpnRouteImport.update({
  id: '/api/public/vnpay/ipn',
  path: '/api/public/vnpay/ipn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/favorites': typeof FavoritesRoute
  '/insights': typeof InsightsRoute
  '/lots': typeof LotsRouteWithChildren
  '/map': typeof MapRoute
  '/booking/new': typeof BookingNewRoute
  '/lots/$deviceId': typeof LotsDeviceIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/booking/$id/pay': typeof BookingIdPayRoute
  '/booking/$id/ticket': typeof BookingIdTicketRoute
  '/api/public/vnpay/ipn': typeof ApiPublicVnpayIpnRoute
  '/api/public/vnpay/return': typeof ApiPublicVnpayReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/favorites': typeof FavoritesRoute
  '/insights': typeof InsightsRoute
  '/lots': typeof LotsRouteWithChildren
  '/map': typeof MapRoute
  '/booking/new': typeof BookingNewRoute
  '/lots/$deviceId': typeof LotsDeviceIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/booking/$id/pay': typeof BookingIdPayRoute
  '/booking/$id/ticket': typeof BookingIdTicketRoute
  '/api/public/vnpay/ipn': typeof ApiPublicVnpayIpnRoute
  '/api/public/vnpay/return': typeof ApiPublicVnpayReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/favorites': typeof FavoritesRoute
  '/insights': typeof InsightsRoute
  '/lots': typeof LotsRouteWithChildren
  '/map': typeof MapRoute
  '/booking/new': typeof BookingNewRoute
  '/lots/$deviceId': typeof LotsDeviceIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/booking/$id/pay': typeof BookingIdPayRoute
  '/booking/$id/ticket': typeof BookingIdTicketRoute
  '/api/public/vnpay/ipn': typeof ApiPublicVnpayIpnRoute
  '/api/public/vnpay/return': typeof ApiPublicVnpayReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/bookings'
    | '/favorites'
    | '/insights'
    | '/lots'
    | '/map'
    | '/booking/new'
    | '/lots/$deviceId'
    | '/api/public/health'
    | '/booking/$id/pay'
    | '/booking/$id/ticket'
    | '/api/public/vnpay/ipn'
    | '/api/public/vnpay/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/bookings'
    | '/favorites'
    | '/insights'
    | '/lots'
    | '/map'
    | '/booking/new'
    | '/lots/$deviceId'
    | '/api/public/health'
    | '/booking/$id/pay'
    | '/booking/$id/ticket'
    | '/api/public/vnpay/ipn'
    | '/api/public/vnpay/return'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/bookings'
    | '/favorites'
    | '/insights'
    | '/lots'
    | '/map'
    | '/booking/new'
    | '/lots/$deviceId'
    | '/api/public/health'
    | '/booking/$id/pay'
    | '/booking/$id/ticket'
    | '/api/public/vnpay/ipn'
    | '/api/public/vnpay/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  FavoritesRoute: typeof FavoritesRoute
  InsightsRoute: typeof InsightsRoute
  LotsRoute: typeof LotsRouteWithChildren
  MapRoute: typeof MapRoute
  BookingNewRoute: typeof BookingNewRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  BookingIdPayRoute: typeof BookingIdPayRoute
  BookingIdTicketRoute: typeof BookingIdTicketRoute
  ApiPublicVnpayIpnRoute: typeof ApiPublicVnpayIpnRoute
  ApiPublicVnpayReturnRoute: typeof ApiPublicVnpayReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lots': {
      id: '/lots'
      path: '/lots'
      fullPath: '/lots'
      preLoaderRoute: typeof LotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lots/$deviceId': {
      id: '/lots/$deviceId'
      path: '/$deviceId'
      fullPath: '/lots/$deviceId'
      preLoaderRoute: typeof LotsDeviceIdRouteImport
      parentRoute: typeof LotsRoute
    }
    '/booking/new': {
      id: '/booking/new'
      path: '/booking/new'
      fullPath: '/booking/new'
      preLoaderRoute: typeof BookingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id/ticket': {
      id: '/booking/$id/ticket'
      path: '/booking/$id/ticket'
      fullPath: '/booking/$id/ticket'
      preLoaderRoute: typeof BookingIdTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id/pay': {
      id: '/booking/$id/pay'
      path: '/booking/$id/pay'
      fullPath: '/booking/$id/pay'
      preLoaderRoute: typeof BookingIdPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vnpay/return': {
      id: '/api/public/vnpay/return'
      path: '/api/public/vnpay/return'
      fullPath: '/api/public/vnpay/return'
      preLoaderRoute: typeof ApiPublicVnpayReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vnpay/ipn': {
      id: '/api/public/vnpay/ipn'
      path: '/api/public/vnpay/ipn'
      fullPath: '/api/public/vnpay/ipn'
      preLoaderRoute: typeof ApiPublicVnpayIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LotsRouteChildren {
  LotsDeviceIdRoute: typeof LotsDeviceIdRoute
}

const LotsRouteChildren: LotsRouteChildren = {
  LotsDeviceIdRoute: LotsDeviceIdRoute,
}

const LotsRouteWithChildren = LotsRoute._addFileChildren(LotsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  FavoritesRoute: FavoritesRoute,
  InsightsRoute: InsightsRoute,
  LotsRoute: LotsRouteWithChildren,
  MapRoute: MapRoute,
  BookingNewRoute: BookingNewRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  BookingIdPayRoute: BookingIdPayRoute,
  BookingIdTicketRoute: BookingIdTicketRoute,
  ApiPublicVnpayIpnRoute: ApiPublicVnpayIpnRoute,
  ApiPublicVnpayReturnRoute: ApiPublicVnpayReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
